### ISSUE TITLE
Is it possible to open the Hubspot's call widget using this calling extension sdk?

### ISSUE THREAD

**Issue by riteshsainju** [HubSpot/calling-extensions-sdk#144]
Actually, I am trying to implement feature for receiving incoming calls. In my application, incoming calls can only be received if the Hubspot's calling widget is already opened. Is there any way, I can receive the incoming calls even if the calling widget is in closed state? Or may be I can send message to hubspot from this calling extension sdk to open the calling widget.

**Comment by alonso-cadenas** [comment]
Hi @riteshsainju, thank you for contacting us. Since we currently do not support incoming calls, I understand that you are looking for a workaround. Unfortunately, our SDK does not offer the ability for your calling app to open the calling widget at this time. However, inbound calling is currently our main priority, and we are targeting to begin alpha testing this new feature in our upcoming alpha release. Our senior partner manager has reached out to you via email and LinkedIn to connect!

**Comment by anitsh** [comment]
Thank you @alonso-cadenas.
Ritesh and our team have receive an invite for the meet.
We are looking forward to it.
