### ISSUE TITLE
JavaScript CDN

### ISSUE THREAD

**Issue by honkimi** [HubSpot/calling-extensions-sdk#25]
I need not "import CallingExtensions from @hubspot/calling-extensions-sdk" but JavaScript CDN.
Can you prepare that?

ex)
<script src="https://app.hubspot.com/callling-extensions-sdk_min.js" type="text/javascript"></script>

**Comment by HarminderSingh1** [comment]
Hi @honkimi - apologies for the late response.  

We have had discussions and decided against deploying the SDK on CDN.  We had an outage due to 3rd party CDN earlier this year.  This SDK is pretty small and shouldn't negatively impact the bundle sizes.  BTW, the main.js in dist folder is UMD and you can include that file directly (../node_modules/@hubspot/calling-extensions-sdk/dist/main.js).  And you can instantiate CallingExtensions as window.default().  Please let me know if this helps.

**Comment by honkimi** [comment]
Thanks for your respornse.
I understand. I will use "node_modules/@hubspot/calling-extensions-sdk/dist/main.js".
