### ISSUE TITLE
Can not overide call provider anymore

### ISSUE THREAD

**Issue by zxdong262** [HubSpot/calling-extensions-sdk#42]
When trying to enable it from browser console. After refresh, still locked
```js
localStorage.setItem( "LocalSettings:Sales:CallingExtensions", '{"name": "RingCentral", "url": "https://xxxx.com"}')
```
<img width="1754" alt="Screen Shot 2021-01-15 at 8 58 53 AM" src="https://user-images.githubusercontent.com/1641949/104667108-4f82d680-5710-11eb-9417-4b1d53701000.png">
<img width="1543" alt="Screen Shot 2021-01-15 at 8 57 35 AM" src="https://user-images.githubusercontent.com/1641949/104667144-5c9fc580-5710-11eb-9213-4aeb9841215b.png">

**Comment by IsaacTakushi** [comment]
Hi, @zxdong262.

We were able to confirm that the lock icon on the "RingCentral" dropdown option had the following tooltip:

![Lock Tooltip](https://user-images.githubusercontent.com/54219937/106154105-40a71580-614d-11eb-91d0-25445bbf31cd.jpg)

Since account **8612069** has trials of _Sales Hub Enterprise_ and _Service Hub Enterprise_, the subscriptions themselves are not the issue.

Instead, I suspect you may be logged in as a user which has not been assigned a paid _Sales Hub_ or _Service Hub_ seat.

Per [this Knowledge Base article](https://knowledge.hubspot.com/calling/integrate-a-third-party-calling-provider-with-hubspot):
> you must have an [assigned _Sales Hub_ or _Service Hub_ paid seat](https://knowledge.hubspot.com/account/manage-sales-hub-and-service-hub-paid-users) to select a third-party calling provider to make a call in HubSpot.

Can you ensure that you are logged in as a user which has been assigned a paid _Sales Hub_ or _Service Hub_ seat?

**Comment by zxdong262** [comment]
@IsaacTakushi Thank you, fixed now.
